services:
  - type: web
    name: rasa-chatbot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: rasa shell --enable-api --cors "*" --port $PORT
    envVars:
      - key: PORT
        value: 10000
